[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

# Compiler settings
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
evm_version = "prague"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
